export enum ConfigurationEnum {
  MONGO_HOST = 'MONGO_HOST',
  MONGO_PASSWORD = 'MONGO_PASSWORD',
  MONGO_USER = 'MONGO_USER',
  MONGO_DATABASE = 'MONGO_DATABASE',
  PORT = 'PORT',
  JWT_KEY = 'JWT_KEY',
  ENABLE_LOGIN_TWO_FACTOR_AUTH = 'ENABLE_LOGIN_TWO_FACTOR_AUTH',
  FRONTEND_URL = 'FRONTEND_URL',
  RESOURCES_BASE_URL = 'RESOURCES_BASE_URL',
}
